/**
 * OpenApi specification - Mogau
 * OpenApi Documentation for User Management System
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ngwatlegodfrey@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserAdminDto { 
    myUsername?: string;
    phone?: string;
    email?: string;
    role?: UpdateUserAdminDto.RoleEnum;
}
export namespace UpdateUserAdminDto {
    export type RoleEnum = 'USER' | 'ADMIN';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum
    };
}


